### ISSUE TITLE
Cannot compile war file from IntelliJ

### ISSUE THREAD

**Issue by mellson** [VueGWT/vue-gwt#48]
Thanks for creating this project! I am trying to add vue-gwt to an existing project I have in IntelliJ and superdevmode is working great 👍 

But when I try to compile to a war using the gwt compiler I get the following errors:
```
 [ERROR] Errors in 'jar:file:/Users/abm/UddataPlus/portal/lib/vue-gwt-1.0-beta-9.jar!/com/axellience/vuegwt/core/client/component/options/VueComponentOptions.java'
      [ERROR] Line 43: No source code is available for type javax.inject.Provider<T>; did you forget to inherit a required module?
   Tracing compile failure path for type 'com.axellience.vuegwt.core.client.component.options.VueComponentOptions'
      [ERROR] Errors in 'jar:file:/Users/abm/UddataPlus/portal/lib/vue-gwt-1.0-beta-9.jar!/com/axellience/vuegwt/core/client/component/options/VueComponentOptions.java'
         [ERROR] Line 43: No source code is available for type javax.inject.Provider<T>; did you forget to inherit a required module?
      [ERROR] Errors in 'jar:file:/Users/abm/UddataPlus/portal/lib/vue-gwt-1.0-beta-9.jar!/com/axellience/vuegwt/core/client/directive/options/VueDirectiveOptions.java'
         [ERROR] com.axellience.vuegwt.core.client.directive.VueDirective cannot be resolved to a type
      [ERROR] Errors in 'jar:file:/Users/abm/UddataPlus/portal/lib/vue-gwt-1.0-beta-9.jar!/com/axellience/vuegwt/core/client/component/IsVueComponent.java'
         [ERROR] com.axellience.vuegwt.core.client.component.VueComponent cannot be resolved to a type
      [ERROR] Errors in 'jar:file:/Users/abm/UddataPlus/portal/lib/vue-gwt-1.0-beta-9.jar!/com/axellience/vuegwt/core/client/directive/VueDirective.java'
         [ERROR] com.axellience.vuegwt.core.client.vnode.VNode cannot be resolved to a type
      [ERROR] Errors in 'jar:file:/Users/abm/UddataPlus/portal/lib/vue-gwt-1.0-beta-9.jar!/com/axellience/vuegwt/core/client/component/VueComponent.java'
         [ERROR] com.axellience.vuegwt.core.client.component.options.VueComponentOptions cannot be resolved to a type
      [ERROR] Errors in 'jar:file:/Users/abm/UddataPlus/portal/lib/vue-gwt-1.0-beta-9.jar!/com/axellience/vuegwt/core/client/vnode/VNode.java'
         [ERROR] com.axellience.vuegwt.core.client.component.IsVueComponent cannot be resolved to a type
```

I have included all transitive dependencies with the library. I am not sure how to move forward and get a build working.

**Comment by adrienbaron** [comment]
Thank you for creating the issue 👍 . Are you using either GIN or Dagger2 in your project?
Vue GWT creates the injection methods in the generated component factories, in case you inject them, so apparently the GWT compiler can't find the source for those interfaces? Not sure why it works in Maven and not in your case though :(

**Comment by mellson** [comment]
Thanks for the reply! I am not using GIN or Dagger2.
For now I'm just trying to recreate the `SimpleLinkComponent` and IntelliJ generates a total of two files for me `SimpleLinkComponentExposedType` && `SimpleLinkComponentFactory`. Does that sound about right or should it be generating more files?

I've narrowed the problem down to the call to `VueGWT.init()` if that's in my code I can't compile, but if that is not in my code I can compile without a problem 🤔 

I've created a simple IntelliJ project showcasing the problem here - https://www.dropbox.com/s/skxs7mykke1b7ej/untitled.zip?dl=0

**Comment by mellson** [comment]
I got it working by adding the interface files from `javax.inject` directly to my src folder. I don't know if it is because this file does not have any source path defined?

**Comment by adrienbaron** [comment]
> I got it working by adding the interface files from `javax.inject` directly to my src folder. I don't know if it is because this [file](https://github.com/VueGWT/vue-gwt/blob/master/core/src/main/java/javax/inject/Inject.gwt.xml) does not have any source path defined?

It might be? If you have time could you try to fix it? You can fork the project and clone the develop branch, do the change, `mvn clean install` it and then try to depend to the Beta-10 SNAPSHOT on your project to see if it fix it 👍. That would be a great first PR 👍

**Comment by mellson** [comment]
Including the sources of `javax.inject` directly was the trick. I have created a pull request https://github.com/VueGWT/vue-gwt/pull/50

I hope the Apache license on javax allows for this.
