### ISSUE TITLE
Implicit boolean value in HTML template

### ISSUE THREAD

**Issue by jtrentes** [VueGWT/vue-gwt#49]
In VueJs, we can declare a boolean prop and write in a HTML template :
`<my-component booleanProp/>`

The prop will be true if present and false if absent. 
But when I try to use this syntax with VueGwt, I get this error:
`Error: (X,X) java: In MyComponent.html at line XX: Passing a String to a non String Prop: "XXX". If you want to pass a boolean or an int you should use v-bind. For example: v-bind:my-prop="12" (or using the short syntax, :my-prop="12") instead of my-prop="12".`

**Comment by adrienbaron** [comment]
Added by this MR: https://github.com/VueGWT/vue-gwt/pull/72
