### ISSUE TITLE
Support .sync Modifier

### ISSUE THREAD

**Issue by mseele** [VueGWT/vue-gwt#55]
Improve vue-gwt by supporting the .sync feature like it's written in
https://vuegwt.github.io/vue-gwt/guide/essentials/components.html#sync-modifier :)

**Comment by adrienbaron** [comment]
Done as part of Beta-10-SNAPSHOT: https://github.com/VueGWT/vue-gwt/commit/799926d34f313d4b1c57469eaba264471604ff5e
