### ISSUE TITLE
cannot integrate with compilation problems

### ISSUE THREAD

**Issue by oedemis** [VueGWT/vue-gwt#56]
i want integrate the framwork in an existing gwt app, but always in mvn install step i receive the error

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project vuegwtmariaexample: Fatal error compiling: java.lang.NoClassDefFoundError: io/bit3/jsass/CompilationException: io.bit3.jsass.CompilationException

also the annotation processor not generate the classes in target/generated-sources/... for examples from the examples of getting started:
LinkComponentExposedType

**Comment by adrienbaron** [comment]
Hi,

Please contact us on Gitter for help with setup: https://gitter.im/VueGWT/vue-gwt
