### ISSUE TITLE
how to run ‘Your First Component # Simple Link Component’

### ISSUE THREAD

**Issue by qinkaiyuan** [VueGWT/vue-gwt#57]
https://vuegwt.github.io/vue-gwt/guide/getting-started.html#your-first-component

general java program right Right click in Main function can show ‘run’ prompt。

but ‘Your First Component # Simple Link Component’ not have Main function  so，how to run this demo program

**Comment by adrienbaron** [comment]
Hi,

Please contact us on Gitter for help with the setup: https://gitter.im/VueGWT/vue-gwt
