### ISSUE TITLE
Catch events from JS in Java

### ISSUE THREAD

**Issue by oedemis** [VueGWT/vue-gwt#58]
How can i catch events from vue js components in java ? 
for example i have vue plugin :
 remove: function(obj) {
	    	   	this.$emit('delete', obj)
			 obj.delete();
    		  }

And i want catch the delete event in Java.

**Comment by adrienbaron** [comment]
Hi @oedemis, for support in the future feel free to ask on Gitter (https://gitter.im/VueGWT/vue-gwt) instead of opening an issue 👍.
To catch an event emitted by a Vue JS Component it works exactly like events from a Vue GWT component, they are essentially the same at runtime.

So for example in the parent component:
```html
<MyJsChild @delete="doSomething"/>
```

Make sure that your parent has the `doSomething` method:
```java
@Method
public void doSomething(MyJSObject obj) {
   // do something with obj
}
```

In this case `MyJSObject` must be a JSInterop Java class representing obj.

**Comment by oedemis** [comment]
I Have integrated the component through JSInterop. it means i have not a template (html) in Java. i integrate the template through js file. I have only the component in java.

@JsComponent ("FromVueJsComponent")
@JsType (isNative = true, namespace = JsPackage.GLOBAL, name = "Object")
public class FromVueJsComponent implements IsVueComponent {
 .. native impls here

**Comment by adrienbaron** [comment]
Yes but I meant the catching of the event is in the parent, meaning where you use your Vue.js component.
At some place you do instantiate that component (`FromVueJsComponent `) in another component template, and that's where you should catch the event.

**Comment by oedemis** [comment]
I have the follwing sitation
I use a third party lib form vuejs ecosystem.

in a JS file i dfined the template and methods etc.. And import it in index.html as script tag
```
window.VueInputTagComponent = Vue.extend({
		    template: `
		    	<div>
		    	<vue-tags-input
	                v-model="tag"
	                :tags="tags"
	                @before-deleting-tag="remove"
            	/>
		      </div>`,
            data:
            methods:
               remove() .....
           computations:
```

Then i host the component in Java over
```
VueGwtWidget<VueInputTagComponent>tagInputWidget
VerticalLayoutContainer vlc
 vlc.add(tagInputWidget);
```
And I have the companion object  VueInputTagComponent which defines the native interfaces.

```
@JsComponent ("VueInputTagComponent")
@JsType (isNative = true, namespace = JsPackage.GLOBAL, name = "Object")
public class VueInputTagComponent implements IsVueComponent {
...
```


but I cannot catch the events that emmited from JS File . for example
the case
```
 @before-deleting-tag="remove"
```
The remove is a native implementation in JS
```
remove: function(obj) {
			    obj.deleteTag();
    		  }
```

In Java I have:
   public native JsObject remove(JsObject obj);

If i make it @JSMethod with the a implementation, the method where not created.

**Comment by adrienbaron** [comment]
Ahh ok, you mount the native Vue component directly. In that case you can use the programmatic way of catching events:
```java
tagInputWidget.vue().$on('my-event-name', (someParam) -> {
   // Do something
})
```

**Comment by oedemis** [comment]
Thank you.
Is there a way to integrate babel for IE in VueGWT. because template literals anony. lambda expressions are not supported in IE

**Comment by adrienbaron** [comment]
GWT should compile all your code to be IE compatible. However if you integrate an external JS you need to make sure it's IE compatible, if not you can just run babel against the file and include the output instead 🙂

**Comment by oedemis** [comment]
what if the my external vue components have a complicated template literals with many v-for and v-ifs. that depends on other extern Vue JS third party components. Is there a toolset where I can generate also the template literals to vue render functions in EcmaScript that also works in IE ?
